# 全断片で共通利用する設定。Step1でFIXし、以降の変更は原則禁止。
project_settings:
  title: "永遠無限森のミステリー"
  overall_theme: "ファンタジー世界における論理的推理の楽しさと、すれ違うコミュニケーションの妙"
  setting_level: "moderate" # ユーザーの要望に基づき、物語に必要な範囲で設定を作成
  common_writing_style:
    base: "葬送のフリーレン風"
    details: |
      キャラクター同士の軽妙で、どこか噛み合わないセリフの応酬を主体とする。
      地の文は淡々としつつも、時折、核心を突くような詩的な描写を挟む。
      物語全体を通して、深刻さや暗い雰囲気は避け、あくまで軽快なエンターテイメントとして構成する。
  key_characters:
    - name: "リラ"
      role: "主人公、エルフの魔法使い"
      profile: "長い時を生きるエルフ。見た目は少女のようだが、話し方や思考は極めて達観している。冷静なツッコミ役で、古代魔法や結界の解読を得意とする。感情の起伏は少ないが、仲間たちの突飛な行動には静かに呆れたり、面白がったりしている。"
    - name: "ゼファー"
      role: "勇者"
      profile: "魔王討伐の使命を背負う若き勇者。正義感は強いが、重度の厨二病。『深淵を歩む者（アビス・ウォーカー）』や『終焉の聖剣（エンドブリンガー）』など、自らの武器や技に大仰な名前を付けている。その言動が、読者に「実は黒幕なのでは？」と疑わせるミスリードの役割を担う。"
    - name: "ボリン"
      role: "ドワーフの戦士"
      profile: "陽気で豪放なドワーフ。上質なエールを何よりも愛しており、常に樽を携帯している。一見すると何も考えていないようだが、長年の経験に裏打ちされた鋭い観察眼と洞察力を持ち、時折、核心を突く「名推理」を披露する。"
    - name: "『観測者』"
      role: "被害者兼、事件の主催者"
      profile: "一万年前に『不老不死の実』を食べたとされる伝説の人物。実の副作用で実体をほとんど失っている。長すぎる生の中で唯一の趣味が『ミステリー』鑑賞・創作となった。今回、何者かに襲われ力を失いかけたが、その状況を逆手に取り、最高の推理劇を上演するために最後の力を振り絞って結界を張った。"
  world_background:
    era: "魔王が世界の半分を支配し、各種族が存亡をかけて抵抗している時代。"
    location: "永遠無限森（エターナルインフィニットフォレスト）"
    key_concepts:
      - concept: "推理無効化の結界"
        description: "特定の空間内において、魔法による情報収集（探知、読心、霊視など）や、論理的思考を補助する魔法の一切を無効化する特殊な結界。古代の言語で術式が組まれており、解読は非常に困難。"
      - concept: "不老不死の実"
        description: "食べると文字通り不老不死になるが、代償として徐々に世界への干渉力を失い、存在が希薄になる呪われた果実。観測者はこれにより、半ば幽霊のような存在となっている。"
  plot_summary:
    - fragment_number: 1
      summary: "冒険者一行（リラ、ゼファー、ボリン）は、魔王城へ向かう途中、永遠無限森で奇妙な結界と一体の死体を発見する。調査のため結界内に入った途端、出入り口が閉ざされ、中に閉じ込められてしまう。"
    - fragment_number: 2
      summary: "閉じ込められた3人は、脱出の手がかりを探すため、魔法に頼らない『オーガニック推理』を開始する。ゼファー、ボリン、リラがそれぞれの視点から推理を披露し、議論を戦わせる。"
    - fragment_number: 3
      summary: "3人の推理を聞き届けた『死体』が突如として復活。自らを『観測者』と名乗り、この状況そのものが趣味で作り上げた推理劇であったことを明かす。真相開示後、一行は魔王城への重要な情報を得る。"
  special_notes: |
    ミステリーのルールを厳格に守ること。「魔法で解決」という展開は絶対に避ける。
    読者に対して「勇者ゼファーが怪しい」と思わせるようなミスリードを、地の文や会話の中に巧妙に配置すること。
    キャラクター名は企画AIが仮で設定したものです。執筆時に違和感があれば変更しても構いませんが、役割とプロファイルは維持してください。 